package it.polimi.ingsw.PSP47.Enumerations;

public enum MessageType {
    REQUEST_CONNECTION, CONNECTION_FAILED, REQUEST_NUMBER_OF_PLAYERS, CONNECTION_ACCEPTED, RANDOM_PLAYER, LIST_OF_GODS,
    NUMBER_PLAYERS, PUBLIC_INFORMATION, UPDATE_SLOT, ERROR, CHOOSE_WORKER, CHOOSE_ACTION, ASK_WORKER_POSITION,
    WAIT_CONNECTION_OPPONENT_PLAYER, OPPONENT_PLAYER_DISCONNECTION, REQUEST_DISCONNECTION, TIMER_UPDATER, FIRST_CONNECTION,
    FIRST_PLAYER_CONNECTION;
}
